# Generated by Django 2.1.7 on 2019-03-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trng_prog_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='user',
        ),
        migrations.AddField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sport',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='specialty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='training_mode',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
