# Generated by Django 2.1.7 on 2019-03-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trng_prog_generator', '0002_auto_20190312_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='sport',
        ),
        migrations.AddField(
            model_name='athlete',
            name='body_weight',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='athlete',
            name='cj_pr',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='athlete',
            name='snatch_pr',
            field=models.FloatField(default=10),
        ),
    ]
